### ISSUE TITLE
replicate repos style for each proposal

### ISSUE THREAD

**Issue by srossross** [openteamsinc/repos#3]
<img width="2036" alt="image" src="https://github.com/user-attachments/assets/0149ceb7-bce4-42f2-a52d-2d1d62980123">

markdown can be formatted in yaml format like this:

```
---
title: Let's make Polars time series operations ergonomic
image: https://storage.googleapis.com/repos-backend/proposal_37db62a8-2a74-43c2-b0ab-f61ca762a5f3.png
funding:
    committed: 50000
    total: 0
sponsors: null
authors: 
 - 'MarcoGorelli'
---
```

Avatar images can be gotten from `https://avatars.githubusercontent.com/MarcoGorelli`

These props should be enough to populate the page
